Repository th3cyb3rhub/TheCyberHUB, pull requests merged in 2022-10, with the labels that each got.

#105 feat: blog page #99
  src/components/Resources/Blogs/Blog.css
  src/components/Resources/Blogs/Blogs.jsx
  src/components/Resources/Blogs/BlogsElements.jsx
  src/components/Resources/Blogs/img.jpg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#107 add: Events Page #100
  src/components/Resources/Events/Capture.png
  src/components/Resources/Events/Events.css
  src/components/Resources/Events/Events.jsx
  src/components/Resources/Events/Events.old.jsx
  src/components/Resources/Events/EventsElement.jsx
  src/components/Resources/Events/EventsElemetns.old.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#110 add and fix: events
  src/assets/CTF-blogImage.png
  src/assets/HacktoberfestXthecyberworld.png
  src/components/Resources/Events/Events.css
  src/components/Resources/Events/Events.jsx
  src/components/Resources/Events/EventsElement.jsx
  src/components/Resources/Events/EventsElementsStyles.jsx
  src/components/Resources/Events/EventsHeader.css
  src/components/Resources/Events/EventsHeader.jsx
  src/components/Resources/WriteUps/WriteUpsElements.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#106 fix: navbar design and typos
  .gitignore
  package-lock.json
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/FooterElements.jsx
  src/components/Homepage/Hero/Hero.jsx
  src/components/Homepage/Info/Data.jsx
  src/components/Homepage/Info/Info.jsx
  src/components/Homepage/Navbar/Navbar.jsx
  src/components/Homepage/Navbar/NavbarElements.jsx
  src/components/MixComponents/Buttons/ButtonElements.jsx
  src/components/MixComponents/ComingSoon.jsx
  src/components/MixComponents/Contribute/Contribute.jsx
  src/components/MixComponents/Contribute/ContributeElements.jsx
  src/components/MixComponents/Spinner/Loader.jsx
  src/components/MixComponents/Spinner/Spinner.jsx
  src/components/MixComponents/Spinner/SpinnerElements.jsx
  src/components/Prep/PrepNavbar/PrepNavbar.jsx
  src/components/Resources/ResourcesNavbar/ResourcesNavbar.jsx
  src/components/Resources/ResourcesNavbar/ResourcesSidebar/ResourcesSidebar.jsx
  src/components/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#109 add dropdown navbar
  src/components/Homepage/Dropdowns/Dropdown.jsx
  src/components/Homepage/Dropdowns/SideDropdown.jsx
  src/components/Homepage/Navbar/Navbar.jsx
  src/components/Homepage/Sidebar/Sidebar.jsx
  src/components/Homepage/Sidebar/SidebarElements.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#118 Added single blog pages
  src/App.jsx
  src/components/Resources/Blogs/AllBlogs.jsx
  src/components/Resources/Blogs/Blog.css
  src/components/Resources/Blogs/Blogs.jsx
  src/components/Resources/Blogs/BlogsData.jsx
  src/components/Resources/Blogs/BlogsElements.jsx
  src/components/Resources/Blogs/ViewBlog.jsx
  src/components/Resources/Blogs/img.webp
  src/pages/Resources.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#122 Add Quiz Categories
  package-lock.json
  src/assets/images/categories.png
  src/assets/videos/demo.mp4
  src/components/Prep/Quiz/Categories/CBQ/CBQ.jsx
  src/components/Prep/Quiz/Categories/CBQ/CBQData.jsx
  src/components/Prep/Quiz/Categories/Categories.jsx
  src/components/Prep/Quiz/Categories/CategoriesButtonData.jsx
  src/components/Prep/Quiz/Categories/CategoriesButtons.jsx
  src/components/Prep/Quiz/Categories/CategoriesElements.jsx
  src/components/Prep/Quiz/Categories/PSQ/PSQ.jsx
  src/components/Prep/Quiz/Categories/PSQ/PSQData.jsx
  src/components/Prep/Quiz/Categories/Phishing/Phishing.jsx
  src/components/Prep/Quiz/Categories/Phishing/PhishingData.jsx
  src/components/Prep/Quiz/Categories/Ransomware/Ransomeware.jsx
  src/components/Prep/Quiz/Categories/Ransomware/RansomewareData.jsx
  src/components/Prep/Quiz/Categories/SRAQ/SRAQ.jsx
  src/components/Prep/Quiz/Categories/SRAQ/SRAQData.jsx
  src/components/Prep/Quiz/Categories/TSSQ/TSSQ.jsx
  src/components/Prep/Quiz/Categories/TSSQ/TSSQData.jsx
  src/components/Prep/Quiz/Categories/VSQ/VSQ.jsx
  src/components/Prep/Quiz/Categories/VSQ/VSQData.jsx
  src/components/Prep/Quiz/Quiz.jsx
  src/components/Prep/Quiz/QuizData.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#147 Fix blog entry overflow on mobile
  src/components/Resources/Blogs/Blog.css
  src/components/Resources/Blogs/BlogsElements.jsx
Labels: 🥗 status: ready for merge

#154 Make Quiz Section responsive
  src/components/Prep/Quiz/Categories/Categories.jsx
  src/components/Prep/Quiz/Categories/CategoriesButtons.jsx
  src/components/Prep/Quiz/Categories/CategoriesElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#166 fix: homepage design
  src/components/Homepage/Info/Data.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#167 Fix homepage design
  src/components/Homepage/Info/Data.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#169 add: fix design and icons
  src/components/Homepage/Info/InfoElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#170 fix: data.jsx
  src/components/Homepage/Info/Data.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#161 URL format changed for blogs
  src/components/Resources/Blogs/AllBlogs.jsx
  src/components/Resources/Blogs/Blogs.jsx
  src/components/Resources/Blogs/ViewBlog.jsx
  src/components/Resources/Blogs/util.js
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#162 fix the responsiveness of the blogs
  src/components/Resources/Blogs/Blog.css
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#163 [FEATURE] Blog card component UI is done
  src/components/Resources/Blogs/Blog.css
  src/components/Resources/Blogs/BlogsData.jsx
  src/components/Resources/Blogs/BlogsElements.jsx
  src/components/Resources/Blogs/ViewBlog.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#171 Fix Sidebar toggle bug
  package-lock.json
  src/components/Navbar/Dropdowns/Dropdown.jsx
  src/components/Navbar/Dropdowns/SideDropdown.jsx
  src/components/Navbar/Sidebar/Sidebar.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#172 Update Blog.css
  src/components/Resources/Blogs/Blog.css
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest

#176 fix: resources url bug
  src/components/Resources/RoadmapResources/RoadmapResources.jsx
Labels: 🥗 status: ready for merge

#178 fix: nav route
  src/components/Homepage/Info/Info.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#181 fix: about nav-item
  src/components/Navbar/Navbar/Navbar.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#182 Add button link to Open-Source page
  src/components/Homepage/Info/Data.jsx
  src/components/Homepage/Info/Info.jsx
  src/components/MixComponents/Buttons/ButtonElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#184 add: upcoming, past events logic and setup
  src/components/Events/Events.jsx
  src/components/Events/Events.old.jsx
  src/components/Events/EventsData/Capture.png
  src/components/Events/EventsData/EventsData.jsx
  src/components/Events/EventsData/HacktoberfestEventData.jsx
  src/components/Events/EventsElement.jsx
  src/components/Events/EventsElementsStyles.jsx
  src/components/Events/EventsElemetns.old.jsx
  src/components/Events/Extra/Events.css
  src/components/Events/Extra/EventsCard.jsx
  src/components/Events/Extra/EventsHeader.css
  src/components/Events/Extra/EventsHeader.jsx
  src/components/Events/OnGoingEvents/OnGoingEvents.jsx
  src/components/Events/OnGoingEvents/OnGoingEventsElements.jsx
  src/components/Events/PastEvents/PastEvents.jsx
  src/components/Events/PastEvents/PastEventsElements.jsx
  src/components/Events/UpComingEvents/UpComingEvents.jsx
  src/components/Events/UpComingEvents/UpComingEventsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, ✔ status: review complete

#188 rm: garbage code
  src/components/Events/Extra/Events.css
  src/components/Events/Extra/EventsCard.jsx
  src/components/Events/Extra/EventsHeader.css
  src/components/Events/Extra/EventsHeader.jsx
  src/components/Events/OnGoingEvents/OnGoingEvents.jsx
  src/components/Events/PastEvents/PastEvents.jsx
  src/components/Events/UpComingEvents/UpComingEvents.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#191 fix: Event Date Issue Resolved
  src/components/Events/Events.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#196 Add Jobs/internship page
  src/components/Community/CommunityElements.jsx
  src/components/Homepage/Info/Info.jsx
  src/components/Prep/Jobs/Job.jsx
  src/components/Prep/Jobs/Jobs.jsx
  src/components/Prep/Jobs/JobsData.jsx
  src/components/Prep/Jobs/JobsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#192 add: spinners
  package-lock.json
  package.json
  src/App.jsx
  src/components/Homepage/Hero/Hero.jsx
  src/components/MixComponents/Spinner/Spinner.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#198 Infinite scroll news
  package-lock.json
  package.json
  src/components/Navbar/Dropdowns/Dropdown.jsx
  src/components/Resources/CyberNews/CyberNews.jsx
  src/services/cyberNewsApi.js
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#202 improve layout and readability of NEWS
  src/components/Resources/CyberNews/CyberNewsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#203 Responsiveness fixes in events page
  package-lock.json
  package.json
  src/components/Events/EventsElement.jsx
  src/components/Events/UpComingEvents/UpComingEventsElements.jsx
  src/components/Prep/Jobs/Jobs.jsx
  src/components/Resources/CyberNews/CyberNewsElements.jsx
  src/components/Resources/WriteUps/WriteUpsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#209 Update CyberSecCoursesData.jsx
  src/components/Learn/Courses/YoutubeCoursesData/CyberSecCoursesData.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#210 Update RoadmapResources.jsx
  src/components/Resources/RoadmapResources/RoadmapResources.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#211 Update BlogsElements.jsx
  src/components/Resources/Blogs/BlogsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#208 fix: typo Jobs.jsx
  src/components/Prep/Jobs/Jobs.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#213 Update ComingSoon.jsx
  src/components/MixComponents/ComingSoon.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#215 fix: alignments
  src/components/Events/PastEvents/PastEventsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#214 Update Homepage.jsx
  src/pages/Homepage.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#212 fix: homepage buttons
  src/components/Homepage/Info/Data.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#217 fix: typo in blogs
  src/components/Resources/Blogs/BlogsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#218 fix: miss-alignment of the events
  src/components/Events/EventsElement.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#204 fixed css issue
  src/components/Prep/Jobs/JobsElements.jsx
Labels: 🥗 status: ready for merge, 🛠 goal: fix, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#224 fix: Alignment issue on the events page
  src/components/Events/EventsElement.jsx
  src/components/Events/OnGoingEvents/OnGoingEventsElements.jsx
  src/components/Events/UpComingEvents/UpComingEventsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#225 Added big nav-bar on hover
  src/components/Navbar/Dropdowns/Dropdown.jsx
  src/components/Navbar/Dropdowns/SideDropdown.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#233 fix: allow buttons to transition without affecting other elements
  src/components/Footer/FooterElements.jsx
  src/components/MixComponents/Buttons/ButtonElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#234 Add Chatbot
  package-lock.json
  package.json
  src/App.jsx
  src/components/Chatbot/ActionProvider.jsx
  src/components/Chatbot/ChatbotElements.jsx
  src/components/Chatbot/MessageParser.jsx
  src/components/Chatbot/TCHBot.jsx
  src/components/Chatbot/Widgets/Assists/AssistElements.jsx
  src/components/Chatbot/Widgets/Assists/AssistLinks.jsx
  src/components/Chatbot/Widgets/Assists/AssistLinksData.jsx
  src/components/Chatbot/Widgets/Assists/AssistOptions.jsx
  src/components/Chatbot/Widgets/BotComponents/TCHBotAvatar.jsx
  src/components/Chatbot/config.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#235 feat: Added routing and sidebox on the course page
  src/App.jsx
  src/components/Learn/Courses/YouTubeVideosElements.jsx
  src/components/Learn/Courses/YoutubeCourseDetail.jsx
  src/components/Learn/Courses/YoutubeCourses.jsx
  src/components/Learn/Courses/YoutubeCoursesLayout.jsx
  src/components/Learn/Courses/YoutubeCoursesSidebar.jsx
  src/components/index.js
  src/pages/Resources.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#244 fix: jobs layout
  src/components/Prep/Jobs/JobsData.jsx
  src/components/Prep/Jobs/JobsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#248 Navbar still remain open Bug Fixed
  src/components/Navbar/Dropdowns/Dropdown.jsx
  src/components/Navbar/Navbar/Navbar.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#249 Remove dropdown icon
  src/components/Prep/Jobs/Jobs.jsx
  src/components/Prep/Jobs/JobsElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#260 added certificate display page.
  package-lock.json
  package.json
  src/assets/images/certificate-bg.png
  src/components/Certificate/Certificate.jsx
  src/components/Certificate/CertificateElements.jsx
  src/components/Certificate/certificate.scss
  src/services/cyberNewsApi.js
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#264 feat: input func to get certificate
  src/App.jsx
  src/components/Certificate/Certificate.jsx
  src/components/Certificate/CertificateElements.jsx
  src/components/Certificate/certificate.scss
  src/components/CyberGames/CTF/CTF.jsx
  src/components/CyberGames/CTF/CTFData.jsx
  src/components/CyberGames/CTF/CTFElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#245 Add new registration page
  src/App.jsx
  src/components/Homepage/Navbar/Navbar.jsx
  src/components/MixComponents/Buttons/ButtonElements.jsx
  src/components/MixComponents/InputField/CustomInputField.jsx
  src/components/Registration/CenterCard.jsx
  src/components/Registration/Form.jsx
  src/components/Registration/Learn2CodePromotion.jsx
  src/pages/Registration.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#262 Redesigned the documentation
  README.md
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#259 fix:navbar menu items collision with each other
  src/components/Navbar/Navbar/NavbarElements.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#257 Footer sticks at bottom with flex & margin
  src/App.jsx
  src/components/Footer/FooterElements.jsx
  src/components/Layout/LayoutElements.jsx
  src/components/Layout/index.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#251 add: image behind the container
  package-lock.json
  package.json
  postcss.config.js
  src/assets/images/projects-bg.png
  src/components/OpenSourceProjects/OpenSourceProjects.css
  tailwind.config.js
  vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#273 refactor [#183]: Migrated blog to styled components.
  src/App.css
  src/components/Certificate/Certificate.jsx
  src/components/Certificate/CertificateElements.jsx
  src/components/Certificate/certificate.scss
  src/components/Learn/Blogs/Blog.css
  src/components/Learn/Blogs/BlogCard.jsx
  src/components/Learn/Blogs/Blogs.jsx
  src/components/Learn/Blogs/ViewBlog.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, hacktoberfest-accepted, hacktoberfest, ✔ status: review complete

#278 add: certificate components
  .eslintcache
  .gitignore
  src/App.css
  src/components/Certificate/Certificate.jsx
  src/components/Certificate/CertificateElements.jsx
  src/components/CyberGames/CTF/CTF.jsx
  src/components/CyberGames/CTF/CTFElements.jsx
Labels: 🥗 status: ready for merge
